filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after
    processors:
      - add_docker_metadata: ~
    containers.ids:
      - '*'

output.logstash:
  hosts: ["logstash-agent:5044"]

logging.level: debug
logging.to_stderr: true

