input {
    redis {
        host => "redis"
        type => "redis-input"
        data_type => "list"
        key => "logstash"
    }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "laravel-logs-%{+YYYY.MM.dd}"
  }
}
