input {
  beats {
    port => 5044
  }
}

filter {
  # Drop unwanted messages
  if ([message] =~ /http_x_real_ip=-/ or
      [message] =~ /^127\.0\.0\.1 - / or
      [message] =~ /^\s*$/ or
      [message] =~ /uncaptured python exception, closing channel/ or
      [message] =~ /supervisord\.py.*Illegal seek/) {
    drop {}
  }

  # Drop messages with DONE or RUNNING
  if [message] =~ /(DONE|RUNNING)/ {
    drop {}
  }

  # Decode unicode in all fields
  ruby {
    code => '
      def decode_unicode(obj)
        case obj
        when String
          obj.gsub(/\\u[\da-fA-F]{4}/) { |m| [m[2..-1].to_i(16)].pack("U*") }
        when Array
          obj.map { |x| decode_unicode(x) }
        when Hash
          obj.each { |k,v| obj[k] = decode_unicode(v) }
        else
          obj
        end
      end

      event.to_hash.each do |field, value|
        next if field.start_with?("@") # Skip metadata fields
        event.set(field, decode_unicode(value))
      end
    '
  }

  # Remove timestamp and level from beginning of the message
  grok {
    match => { "message" => "^\[%{TIMESTAMP_ISO8601:timestamp}\] %{WORD:env}\.%{WORD:level}: %{GREEDYDATA:json_part}" }
    tag_on_failure => ["grok_failure"]
  }

  mutate {
    rename => { "json_part" => "message" }
  }
}

output {
    redis {
        host => "redis"
        data_type => "list"
        key => "logstash"
    }
}
